// Pre-generates Disha's spoken lines as audio files using Sarvam AI's Bulbul TTS
// (voice "ritu"), so the demo plays real audio with no live API calls at runtime.
// Run with: npm run gen-audio (requires SARVAM_API_KEY in .env)
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

function loadEnv() {
  const path = join(root, '.env');
  if (!existsSync(path)) return {};
  const out = {};
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    const m = line.match(/^\s*([\w.-]+)\s*=\s*(.*)\s*$/);
    if (m) out[m[1]] = m[2].replace(/^["']|["']$/g, '');
  }
  return out;
}

const env = { ...loadEnv(), ...process.env };
const API_KEY = env.SARVAM_API_KEY;
if (!API_KEY) {
  console.error('Missing SARVAM_API_KEY (set it in .env or the environment).');
  process.exit(1);
}

const SPEAKER = 'ritu';
const MODEL = 'bulbul:v3';
const LANGUAGE_CODE = 'en-IN';

const { OPENING_LINE, EXPLORE_SCRIPT, REVEAL_LINES, AFTER_ACCEPT } = await import('../src/data/script.js');

const lines = [
  OPENING_LINE,
  ...EXPLORE_SCRIPT.filter((l) => l.kind === 'd'),
  ...REVEAL_LINES.filter((l) => l.kind === 'd'),
  AFTER_ACCEPT,
].filter((l) => l.id);

const outDir = join(root, 'public', 'audio');
mkdirSync(outDir, { recursive: true });

const FORCE = process.argv.includes('--force');

// Reads a PCM WAV's duration in ms by walking its RIFF chunks (handles extra
// chunks like LIST/fact that some TTS services insert before "data").
function wavDurationMs(buf) {
  let offset = 12; // past "RIFF"<size>"WAVE"
  let sampleRate = 0, channels = 0, bitsPerSample = 0, dataSize = 0;
  while (offset + 8 <= buf.length) {
    const id = buf.toString('ascii', offset, offset + 4);
    const size = buf.readUInt32LE(offset + 4);
    const body = offset + 8;
    if (id === 'fmt ') {
      channels = buf.readUInt16LE(body + 2);
      sampleRate = buf.readUInt32LE(body + 4);
      bitsPerSample = buf.readUInt16LE(body + 14);
    } else if (id === 'data') {
      dataSize = size;
    }
    offset = body + size + (size % 2); // chunks are word-aligned
  }
  if (!sampleRate || !channels || !bitsPerSample || !dataSize) return null;
  const bytesPerSec = sampleRate * channels * (bitsPerSample / 8);
  return Math.round((dataSize / bytesPerSec) * 1000);
}

const manifest = {};

for (const line of lines) {
  const fileName = `${line.id}.wav`;
  const filePath = join(outDir, fileName);

  if (!FORCE && existsSync(filePath)) {
    console.log(`Skipping "${line.id}" (already generated; use --force to redo).`);
  } else {
    console.log(`Generating "${line.id}" (${line.text.length} chars)...`);
    const res = await fetch('https://api.sarvam.ai/text-to-speech', {
      method: 'POST',
      headers: {
        'api-subscription-key': API_KEY,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        text: line.text,
        language_code: LANGUAGE_CODE,
        speaker: SPEAKER,
        model: MODEL,
        speech_sample_rate: 24000,
      }),
    });

    if (!res.ok) {
      const body = await res.text();
      throw new Error(`Sarvam TTS failed for "${line.id}": ${res.status} ${body}`);
    }

    const data = await res.json();
    const b64 = data.audios?.[0];
    if (!b64) throw new Error(`No audio returned for "${line.id}": ${JSON.stringify(data)}`);

    writeFileSync(filePath, Buffer.from(b64, 'base64'));
  }

  const buf = readFileSync(filePath);
  const ms = wavDurationMs(buf) ?? 1500;
  manifest[line.id] = { url: `audio/${fileName}`, ms };
  console.log(`  -> public/audio/${fileName} (${buf.length} bytes, ${ms}ms)`);
}

const manifestSrc = `// Generated by scripts/generate-tts.mjs — do not edit by hand.\nexport const AUDIO = ${JSON.stringify(manifest, null, 2)};\n`;
writeFileSync(join(root, 'src', 'data', 'audio.js'), manifestSrc);
console.log(`\nWrote src/data/audio.js with ${Object.keys(manifest).length} entries.`);
